services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres123
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 17022025
      POSTGRES_DB: mhgh
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mhgh-network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_URL: postgres://postgres:17022025@postgres:5432/mhgh
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mhgh-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mhgh-network

volumes:
  postgres_data:

networks:
  mhgh-network:
    driver: bridge
