services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres123
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mhgh-network

  backend:
    build:
      context: ./backend
    container_name: backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
      HOST: ${HOST}
      REDIS_URL: ${REDIS_URL}
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - mhgh-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - mhgh-network

  redis:
    image: redis:7-alpine
    container_name: redis-mhgh
    ports:
      - "6380:6379"
    networks:
      - mhgh-network

volumes:
  postgres_data:

networks:
  mhgh-network:
    driver: bridge